# Generated by Django 5.1.5 on 2025-01-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('teaching_performance', models.PositiveIntegerField(help_text='Percentage score for teaching performance')),
                ('research_performance', models.PositiveIntegerField(help_text='Percentage score for research performance')),
                ('student_feedback', models.PositiveIntegerField(help_text='Percentage score for student feedback')),
                ('overall_performance', models.PositiveIntegerField(help_text='Overall performance percentage')),
            ],
        ),
    ]
