# Generated by Django 5.1.5 on 2025-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('courses_taught', models.IntegerField()),
                ('highest_qualification', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('is_current_advisor', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField()),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('research_interests', models.TextField()),
            ],
        ),
    ]
